<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Version>9.8.2.3</Version>
    <AssemblyVersion>9.8.2.3</AssemblyVersion>
    <FileVersion>9.8.2.3</FileVersion>
    <RootNamespace>WFInfo.Linux</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>Resources/WFLogo.ico</ApplicationIcon>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.18" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.18" />

    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.18" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WFInfo.Core\WFInfo.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\WFLogo.png" />
    <EmbeddedResource Include="Resources\achievment_03.wav" />
    <EmbeddedResource Include="Resources\Notifications\anxious.ogg" />
    <EmbeddedResource Include="Resources\Notifications\bubbling-up.ogg" />
    <EmbeddedResource Include="Resources\Notifications\hold-on.ogg" />
    <EmbeddedResource Include="Resources\Notifications\maybe-one-day.ogg" />
    <EmbeddedResource Include="Resources\Notifications\slow-spring-board.ogg" />
    <EmbeddedResource Include="Resources\Notifications\time-is-now.ogg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AppImage\wfinfo-setup-input.sh" CopyToOutputDirectory="PreserveNewest" Link="wfinfo-setup-input.sh" />
  </ItemGroup>
</Project>